name: .NET with Reactor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Increment version
      id: version_bump
      run: |
        FILE_PATH='./ShipRight.csproj'
        # Use awk to extract the version directly without relying on Perl-compatible regular expressions
        VERSION=$(awk -F'[<>]' '/<Version>/{print $3}' "$FILE_PATH")
        IFS='.' read -ra ADDR <<< "$VERSION"
        ADDR[2]=$((ADDR[2]+1)) # Increment patch version
        NEW_VERSION="${ADDR[0]}.${ADDR[1]}.${ADDR[2]}"
        # Use sed to replace the version in the csproj file
        sed -i "s/<Version>$VERSION<\/Version>/<Version>$NEW_VERSION<\/Version>/" "$FILE_PATH"
        echo "New version: $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      shell: bash


    - name: Commit version bump
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -u
        git commit -m "Bump version to $NEW_VERSION"
        git push


    - name: Restore dependencies
      run: dotnet restore ShipRight.csproj

    - name: Build
      run: dotnet build ShipRight.csproj --configuration Release --no-restore -p:Platform=x86

    - name: Execute .NET Reactor
      run: |
        $ReactorPath = "$env:GITHUB_WORKSPACE\tools\dotnet-reactor\dotNET_Reactor.Console.exe"
        $FilePath = "$env:GITHUB_WORKSPACE\bin\x86\Release\net8.0-windows\ShipRight.dll"
        $ProjectPath = "$env:GITHUB_WORKSPACE\ShipRight.nrproj"
        & "$ReactorPath" -file "$FilePath" -project "$ProjectPath" -targetfile "$FilePath" -verbose
      shell: pwsh

    - name: Upload main build artifacts (without PDB)
      uses: actions/upload-artifact@v3
      with:
        name: ShipRight_Manual_${{ env.NEW_VERSION }}
        path: |
          ${{ github.workspace }}/bin/x86/Release/net8.0-windows/**
          !${{ github.workspace }}/bin/x86/Release/net8.0-windows/**/*.pdb

    - name: Upload PDB file only
      uses: actions/upload-artifact@v3
      with:
        name: ShipRight_Manual_${{ env.NEW_VERSION }}_PDB
        path: ${{ github.workspace }}/bin/x86/Release/net8.0-windows/**/*.pdb
